<?php

namespace Acme\CustomersBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SwindlerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SwindlerRepository extends DocumentRepository
{
}